#%RAML 0.8

title: Acme API
version: 3
baseUri: http://127.0.0.1:8000/api/v{version}/
documentation:
  - title: Getting started
    content: |
      ###Hello
      I am a `firendly` *API*.
  - title: Authentication
    content: |
      Documentaion content.

/books:
  get:
    queryParameters:
      author:
        displayName: Author
        type: string
        description: An author's full name
        example: Mary Roach
        required: false
      publicationYear:
        displayName: Pub Year
        type: number
        description: The year released for the first time in the US
        example: 1984
        required: false
      rating:
        displayName: Rating
        type: number
        description: Average rating (1-5) submitted by users
        example: 3.14
        required: false
      isbn:
        displayName: ISBN
        type: string
        minLength: 10
        example: 0321736079?
  put:
  post:
    body:
      application/json:
        example: |
          {
            "kaka": "lala"
          }
  /{bookTitle}:
    get:
    put:
    delete:
      /author:
      get:
      /publisher:
      get:

/mama:
  get:
