#%RAML 0.8

title: Acme API
version: 3
baseUri: http://127.0.0.1:8000/api/v{version}/

documentation:
  - title: Getting started
    content: |
      ###Hello
      I am a `firendly` *API*.
  - title: Authentication
    content: |
      twefa

          :::python
          def python():
            pass

